name: Approval Gate

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build
