name: Call Template Workflow

on: 
  workflow_dispatch:

jobs:
  job:
    runs-on: windows-latest

    steps:
    - name: Print message from caller workflow 
      run: echo "This message is from the caller workflow"

  call-template-workflow:
    uses: siddhant09/.github/.github/workflows/template-workflow.yml@main
