name: Clean Up

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with: 
        days: 7
        repository: ${{ github.repository }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
