name: .NET Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Cache Depencency
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/.csproj', '**/*.sln') }}
        restore-keys: ${{ runner.os }}-nuget

    - name: Restore Dependency
      run: dotnet restore

    - name: Build
      run: dotnet build

    - name: Test
      run: dotnet test
