name: Secrets and Variables

on:
  workflow_dispatch:

env:
  workflow_variable: "workflow_variable is scopped for the whole workflow"

jobs:
  variables_job:
    runs-on: ubuntu-latest

    env:
      variables_job_variable: "variables_job_variable is scopped in this job only"

    steps:
    - run: |
        echo ${{ env.workflow_variable }}
        echo ${{ env.variables_job_variable }}
        echo ${{ secrets.TEST_SECRET }}
        
  another_variables_job:
    runs-on: ubuntu-latest

    steps:
    - run: |
        echo ${{ env.workflow_variable }}
        echo ${{ env.variables_job_variable }}
        echo ${{ secrets.TEST_SECRET }}
