name: Webhook Event

on:
  repository_dispatch:
    types:
      - webhook

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
    - name: Print
      run: echo "This workflow will be triggered by a webhook"
    
